singleServerConfig:
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  dnsMonitoringInterval: 5000
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  database: 0
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  sslProtocols: null
  sslEnableEndpointIdentification: true
  sslProvider: JDK
  sslTruststore: null
  sslTruststorePassword: null
  sslKeystore: null
  sslKeystorePassword: null
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: false